name: Matrix Demo
on: 
    push:
        branches: 
            - master
jobs:
    build:
        continue-on-error: true
        strategy:
            matrix:
                node-version: [20, 22, 24]
                operating-systems: [ubuntu-latest, windows-latest]
                include:
                    - node-version: 24
                      operating-systems: macos-latest
                exclude:
                    - node-version: 20
                      operating-systems: windows-latest
        runs-on: ${{ matrix.operating-systems}}
        steps:
            - name: Get Code
              uses: actions/checkout@v4
            - name: Install Node
              uses: actions/setup-node@v6
              with:
                node-version: ${{ matrix.node-version}}
            - name: Install dependecies
              run: npm ci
            - name: Build
              run: npm run build

