name: Resuable Deploy
on: 
    workflow_call:
        inputs:
            artifact-name:
                description: 'Name of the artifact to download'
                required: false
                default: dist
                type: string
        outputs:
            result:
                description: 'Result of the deployment'
                value: ${{ jobs.deploy.outputs.result }}
jobs:
    deploy:
        runs-on: ubuntu-latest
        outputs:
            result: ${{ steps.set-output.outputs.result }}
        steps:
            - name: Get build artifacts
              uses: actions/download-artifact@v6
              with:
                name: ${{ inputs.artifact-name }}
            - name: Display artifact contents
              run: ls
            - name: Deploy
              run: echo "Deploying..."
            - name: Set output
              id: set-output
              run: echo "result=Success" >> $GITHUB_OUTPUT